# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages
latex: false


branches:
  only:
  - master
  - packagedoc


matrix:
  include:
    - r: 3.3
    - r: release
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

addons:
  apt:
    packages:
      - libgit2-dev

