# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages
latex: false

r_packages:
  - covr

matrix:
  include:
    - r: 3.3
    - r: release
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - libgit2-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
