# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

matrix:
  include:
  - r:
    - oldrel
    - release
    addons:
      apt:
        packages:
          - libgit2-dev

  - r: release
    os: osx
    osx_image: xcode7.3



